export interface producto {
  id: string;
  nombre: string;
  idProductoSiesa?: string;
  esCostoDirecto?: boolean;
  consumptionDocTypes: string[];
  productionDocTypes: string[];
  consumptionDocIds?: number[];
  productionDocIds?: number[];
  consumptionDocOrden?: number[];
  productionDocOrden?: number[];
  consumptionDocOrigenIds?: string[];
  productionDocOrigenIds?: string[];
  metaActual?: number;
  esCompuesto?: boolean;
  componenteSiesaIds?: string[];
  usaSuma?: boolean;
  sentidoMeta?: boolean;
  mostrarCmi?: boolean;
  produccionBaseId?: string;
  metaDiariaManual?: boolean;
  idProductoTbs?: string;
  idTbsTipoDoc?: string;
  tbsDescripcion?: string;
  seccionId?: number;
  seccionNombre?: string;
  ordenReporte?: number;
  formulaOperadores?: string[];
}